apiVersion: apps/v1
kind: Deployment
metadata:
  name: comment-service-deployment
  labels:
    app: comment-service
spec:
  replicas: 2
  selector:
    matchLabels:
      app: comment-service
  template:
    metadata:
      labels:
        app: comment-service
    spec:
      containers:
        - name: comment-service
          image: serhatgundem/comment-service:latest
          ports:
            - containerPort: 8000
          env:
            - name: BLOG_SERVICE_URL
              value: "http://blog-service:8000"
            - name: USER_SERVICE_URL
              value: "http://user-service:8000"
          volumeMounts:
            - name: comment-sqlite-storage
              mountPath: /app/db.sqlite3
              subPath: db.sqlite3
      imagePullSecrets:
        - name: regcred
      volumes:
        - name: comment-sqlite-storage
          persistentVolumeClaim:
            claimName: comment-sqlite-pvc
