version: "3.12"

services:
  web:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    environment:
      - DEBUG=True
    command:
      [
        "/bin/sh",
        "-c",
        "python manage.py migrate && python manage.py runserver 0.0.0.0:8000",
      ]
