apiVersion: apps/v1
kind: Deployment
metadata:
  name: blog-service-deployment
  labels:
    app: blog-service
spec:
  replicas: 2
  selector:
    matchLabels:
      app: blog-service
  template:
    metadata:
      labels:
        app: blog-service
    spec:
      containers:
        - name: blog-service
          image: serhatgundem/blog-service:latest
          ports:
            - containerPort: 8000
          env:
            - name: USER_SERVICE_URL
              value: "http://user-service:8000"
          volumeMounts:
            - name: blog-sqlite-storage
              mountPath: /app/db.sqlite3
              subPath: db.sqlite3
      imagePullSecrets:
        - name: regcred
      volumes:
        - name: blog-sqlite-storage
          persistentVolumeClaim:
            claimName: blog-sqlite-pvc
